# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e035cb8d2ec1d4cbc492c11feea16a597b6c77e35be760ab436bb183ea2f5a0084a3b237fe359ac00f5bfd066693bf65489e4cdcdd75207122fc41c0845346b

test:
  secret_key_base: f700febec001bcbebcfe6820b6c3460497e9575bf77f393b9fda8b2cfab5210204874bb4f5fca8865ca61a802fc44bf1ecfcab2ba10970d0c2404d061fc4096f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
